# Generated by Django 4.0.2 on 2022-08-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='https://res.cloudinary.com/cloudofmrguardian/image/upload/v1661686965/default_edwmc9.png', max_length=10000, null=True),
        ),
    ]
