# Generated by Django 4.1 on 2022-11-03 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, default=[], null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
