# Generated by Django 4.1 on 2022-11-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_groupmessage_alter_group_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='messages',
            field=models.ManyToManyField(blank=True, default=[], null=True, to='core.groupmessage'),
        ),
    ]
