# Generated by Django 4.1 on 2022-11-08 02:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='roomID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
